Feature 1
MrBarracuda/axios-ts pull request #1
Opened 2022-10-03 09:32 UTC by MrBarracuda

2022-10-03 12:38 UTC, Ksuzi requested changes

2022-10-03 12:38 UTC, Ksuzi commented on src/App.tsx
> +                <Routes>
Please, create the separate component for routing

2022-10-03 12:38 UTC, Ksuzi commented on src/components/BlogDetails/BlogDetails.styles.ts
> +  & div {
`& `sign is not necessary for direct child element

2022-10-03 12:38 UTC, Ksuzi commented on src/components/Create/Create.tsx
> +        | ChangeEvent<HTMLSelectElement>
Please define the type outside of the component

2022-10-03 12:38 UTC, Ksuzi commented on src/components/Create/Create.tsx
> +                    <option value="mario">mario</option>
The options for author could be generated from fetched blogs

2022-10-03 12:38 UTC, Ksuzi commented on src/App.tsx
> +                    <Route path={'/create'} element={<Create/>}/>
You reuse the same link in a few components - better to define the constant for routes

2022-10-03 12:38 UTC, Ksuzi commented on src/constants.ts
> +export const PRIMARY_COLOR = '#f1356d';
FYI - better not to mix the styles constants and endpoint constants

2022-10-03 12:38 UTC, Ksuzi commented on src/hooks/useFetch.ts
> +    // useEffect(() => getData(), [])
Remove the commented code

2022-10-03 12:38 UTC, Ksuzi commented on src/index.css
>  }
Delete css file and move all styles to styled-components

2022-10-03 12:38 UTC, Ksuzi commented on src/services/api/baseURL.tsx
> +    baseURL: 'http://localhost:8000/'
BaseURL should be stored in .env file and be encapsulated

2022-10-03 12:40 UTC, MrBarracuda commented on src/hooks/useFetch.ts
> +    // useEffect(() => getData(), [])
done

2022-10-03 12:51 UTC, MrBarracuda commented on src/components/BlogDetails/BlogDetails.styles.ts
> +  & div {
done

2022-10-03 13:12 UTC, MrBarracuda commented on src/services/api/baseURL.tsx
> +    baseURL: 'http://localhost:8000/'
done

2022-10-03 13:33 UTC, MrBarracuda commented on src/constants.ts
> +export const PRIMARY_COLOR = '#f1356d';
done

2022-10-03 13:35 UTC, MrBarracuda commented on src/components/Create/Create.tsx
> +                    <option value="mario">mario</option>
done, but has to reconsider the way of adding authors to a blog

2022-10-03 14:13 UTC, MrBarracuda commented
routing has to be done

2022-10-04 14:49 UTC, MrBarracuda commented on src/App.tsx
> +                <Routes>
done :)

2022-10-04 14:57 UTC, Ksuzi requested changes

2022-10-04 14:57 UTC, Ksuzi commented on .env
> +REACT_APP_AXIOS_API_URL='http://localhost:8000/'
you have to remove this file manually -> push the deletion changes -> re-create it again (to remove the file from git)

also create the `.env.example`
so that you will be able to define file with empty variables that will be a pointer to what values need to be provided by the developer

2022-10-04 14:57 UTC, Ksuzi commented on src/components/Create/Create.tsx
> +export const Create = ({blogs, error, isLoading}: any) => {
😱😱😱😱😱

2022-10-04 14:59 UTC, MrBarracuda commented on src/components/Create/Create.tsx
> +export const Create = ({blogs, error, isLoading}: any) => {
it's temporary solution :D

2022-10-04 21:14 UTC, MrBarracuda commented on .env
> +REACT_APP_AXIOS_API_URL='http://localhost:8000/'
done

2022-10-04 21:15 UTC, MrBarracuda commented on src/components/Create/Create.tsx
> +export const Create = ({blogs, error, isLoading}: any) => {
done, I need the explanation why it works now

2022-10-04 21:15 UTC, MrBarracuda commented on src/App.tsx
> +                    <Route path={'/create'} element={<Create/>}/>
done

2022-12-04 21:20 UTC, closed without merging